import React, { useState } from 'react';
import { TriageStatus } from '../types';
import { 
  Activity, 
  AlertTriangle, 
  HeartPulse, 
  Hospital, 
  Ban, 
  Stethoscope, 
  Siren, 
  CheckCircle2,
  FileSearch,
  Ambulance,
  X,
  MapPin,
  Navigation
} from 'lucide-react';

interface StatusHUDProps {
  status: TriageStatus | null;
  isActive: boolean;
  isAnalyzing?: boolean;
}

const StatusHUD: React.FC<StatusHUDProps> = ({ status, isActive, isAnalyzing }) => {
  const [emsMode, setEmsMode] = useState(false);

  if (!status && !isAnalyzing) {
    return (
      <div className="absolute top-4 right-4 z-20 w-full max-w-sm bg-black/60 backdrop-blur-md border border-zinc-800 rounded-xl p-6 text-zinc-400 shadow-2xl transition-all">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-2 h-2 rounded-full bg-zinc-500 animate-pulse" />
          <span className="text-xs font-mono uppercase tracking-widest text-zinc-500">System Standby</span>
        </div>
        <div className="space-y-4">
          <p className="text-sm leading-relaxed text-zinc-300">
            <strong className="text-white block mb-1">Ready to Triage.</strong>
            Describe symptoms, show injuries, or upload medical reports (ECG, Prescriptions).
          </p>
          <div className="flex gap-2 opacity-50">
            <Activity className="w-4 h-4" />
            <Stethoscope className="w-4 h-4" />
            <HeartPulse className="w-4 h-4" />
          </div>
        </div>
      </div>
    );
  }

  if (isAnalyzing) {
    return (
       <div className="absolute top-4 right-4 z-20 w-full max-w-sm bg-black/80 backdrop-blur-xl border border-blue-500/30 rounded-xl p-6 shadow-[0_0_30px_rgba(59,130,246,0.2)]">
         <div className="flex flex-col items-center justify-center gap-4 py-8">
            <div className="relative">
              <div className="w-12 h-12 border-4 border-blue-500/30 border-t-blue-500 rounded-full animate-spin"></div>
              <FileSearch className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-5 h-5 text-blue-400" />
            </div>
            <p className="text-blue-200 font-mono text-sm animate-pulse">GEMINI 3 PRO ANALYZING...</p>
         </div>
       </div>
    );
  }

  if (!status) return null;

  // EMS HANDOVER MODE VIEW
  if (emsMode) {
    return (
      <div className="absolute inset-0 z-50 bg-white text-black p-6 flex flex-col animate-in fade-in duration-300">
        <div className="flex justify-between items-start mb-6">
          <div>
            <h1 className="text-3xl font-black uppercase tracking-tighter mb-1">EMS Handover Report</h1>
            <p className="text-sm font-mono text-zinc-600">Generated by LifeLine AI • {new Date(status.lastUpdated).toLocaleTimeString()}</p>
          </div>
          <button onClick={() => setEmsMode(false)} className="p-2 bg-black text-white rounded-full">
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 flex-grow overflow-y-auto">
          <div className="border-4 border-black p-4">
             <span className="block text-xs font-black uppercase mb-2 bg-black text-white px-2 py-1 w-max">Presenting Condition</span>
             <p className="text-4xl font-bold leading-none">{status.condition}</p>
          </div>
          
          <div className={`border-4 p-4 ${status.riskLevel === 'EMERGENCY' ? 'border-red-600 bg-red-50' : 'border-black'}`}>
             <span className="block text-xs font-black uppercase mb-2 bg-black text-white px-2 py-1 w-max">Triage Category</span>
             <p className={`text-4xl font-bold leading-none ${status.riskLevel === 'EMERGENCY' ? 'text-red-600' : 'text-black'}`}>{status.riskLevel}</p>
          </div>

          <div className="border-4 border-black p-4 md:col-span-2">
             <span className="block text-xs font-black uppercase mb-2 bg-black text-white px-2 py-1 w-max">Clinical Reasoning</span>
             <p className="text-xl font-medium leading-relaxed">{status.reasoning}</p>
          </div>

          <div className="border-4 border-black p-4">
             <span className="block text-xs font-black uppercase mb-2 bg-black text-white px-2 py-1 w-max">Action Taken</span>
             <p className="text-lg">{status.immediateAction}</p>
          </div>
           
           <div className="border-4 border-black p-4">
             <span className="block text-xs font-black uppercase mb-2 bg-black text-white px-2 py-1 w-max">Contraindications</span>
             <p className="text-lg font-bold text-red-600">{status.contraindications}</p>
          </div>
        </div>
      </div>
    );
  }

  // STANDARD USER VIEW
  const getSeverityConfig = (level: string) => {
    switch (level) {
      case 'EMERGENCY': 
        return {
          color: 'text-red-500',
          bg: 'bg-red-950/80',
          border: 'border-red-500',
          icon: Siren,
          shadow: 'shadow-[0_0_50px_rgba(239,68,68,0.3)]'
        };
      case 'MODERATE': 
        return {
          color: 'text-orange-500',
          bg: 'bg-orange-950/80',
          border: 'border-orange-500',
          icon: AlertTriangle,
          shadow: 'shadow-[0_0_30px_rgba(249,115,22,0.2)]'
        };
      case 'LOW': 
        return {
          color: 'text-emerald-500',
          bg: 'bg-emerald-950/80',
          border: 'border-emerald-500',
          icon: CheckCircle2,
          shadow: 'shadow-[0_0_30px_rgba(16,185,129,0.2)]'
        };
      default: 
        return {
          color: 'text-zinc-500',
          bg: 'bg-zinc-900/90',
          border: 'border-zinc-700',
          icon: Activity,
          shadow: ''
        };
    }
  };

  const config = getSeverityConfig(status.riskLevel);
  const Icon = config.icon;

  return (
    <div className="absolute top-4 right-4 z-20 w-full max-w-md flex flex-col gap-3 h-[calc(100vh-100px)] overflow-y-auto pb-10 scrollbar-hide">
      
      {/* Primary Triage Card */}
      <div className={`backdrop-blur-xl border-2 rounded-xl p-5 ${config.bg} ${config.border} ${config.shadow} transition-all duration-500`}>
        <div className="flex items-center justify-between mb-4 border-b border-white/10 pb-3">
          <div className="flex items-center gap-2">
            <Icon className={`w-6 h-6 ${config.color} animate-pulse`} />
            <h2 className={`text-xl font-bold font-mono tracking-tight ${config.color}`}>
              {status.riskLevel} PRIORITY
            </h2>
          </div>
          {status.source === 'DEEP_SCAN' && (
             <span className="text-[10px] bg-blue-500/20 text-blue-300 px-2 py-0.5 rounded border border-blue-500/30 font-mono">
               DEEP SCAN
             </span>
          )}
        </div>
        
        <div className="space-y-4">
          <div>
            <span className="text-xs uppercase font-bold text-white/50 block mb-1">Probable Condition</span>
            <p className="text-2xl font-bold text-white leading-none">{status.condition}</p>
          </div>

          <div className="bg-black/30 rounded-lg p-3 border border-white/5">
            <span className="text-xs uppercase font-bold text-white/50 block mb-1">Reasoning</span>
            <p className="text-sm text-zinc-300 leading-relaxed">{status.reasoning}</p>
          </div>
        </div>
      </div>

      {/* Recommended Hospital Card (NEW) */}
      {status.recommendedHospital && (
        <div className="bg-blue-950/40 backdrop-blur-md border border-blue-500/30 rounded-xl p-4 shadow-lg animate-in slide-in-from-right-4 duration-500">
           <div className="flex items-center justify-between mb-3">
             <div className="flex items-center gap-2">
               <Navigation className="w-4 h-4 text-blue-400" />
               <h3 className="text-sm font-bold text-blue-100">Recommended Facility</h3>
             </div>
             <span className="text-xs font-mono text-blue-300">{status.recommendedHospital.travelTime}</span>
           </div>
           
           <div className="space-y-1">
             <p className="text-lg font-bold text-white leading-tight">{status.recommendedHospital.name}</p>
             <p className="text-xs text-zinc-400">{status.recommendedHospital.address}</p>
           </div>
           
           <div className="mt-3 flex gap-2">
             <a 
               href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(status.recommendedHospital.name + ' ' + status.recommendedHospital.address)}`}
               target="_blank"
               rel="noreferrer"
               className="flex-1 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold py-2 rounded text-center transition-colors"
             >
               Open Maps
             </a>
           </div>
        </div>
      )}

      {/* Action Plan */}
      <div className="bg-zinc-900/90 backdrop-blur-md border border-zinc-700 rounded-xl overflow-hidden shadow-xl">
        <div className="p-3 bg-zinc-800/50 border-b border-zinc-700 flex items-center gap-2">
           <Activity className="w-4 h-4 text-blue-400" />
           <span className="text-sm font-bold text-zinc-300 uppercase tracking-wider">Protocol</span>
        </div>
        
        <div className="p-5 space-y-5">
           {/* First Aid */}
           <div>
             <h3 className="text-sm font-medium text-emerald-400 mb-2 flex items-center gap-2">
               <HeartPulse className="w-4 h-4" /> Immediate Action
             </h3>
             <p className="text-sm text-zinc-100 bg-emerald-950/30 border border-emerald-900/50 p-3 rounded-lg">
               {status.immediateAction}
             </p>
           </div>

           {/* Hospital Urgency */}
           <div className="grid grid-cols-2 gap-3">
              <div className="bg-zinc-950 p-3 rounded-lg border border-zinc-800">
                 <span className="text-xs text-zinc-500 block mb-1">Disposition</span>
                 <div className={`text-sm font-bold ${status.hospitalUrgency === 'RUSH_TO_ER' ? 'text-red-500' : 'text-zinc-200'}`}>
                    {status.hospitalUrgency.replace(/_/g, ' ')}
                 </div>
              </div>
              <div className="bg-zinc-950 p-3 rounded-lg border border-zinc-800">
                 <span className="text-xs text-zinc-500 block mb-1">Department</span>
                 <div className="text-sm font-bold text-blue-300 flex items-center gap-1">
                    <Hospital className="w-3 h-3" />
                    {status.department}
                 </div>
              </div>
           </div>

           {/* Contraindications */}
           <div>
              <h3 className="text-sm font-medium text-red-400 mb-2 flex items-center gap-2">
                <Ban className="w-4 h-4" /> Do NOT Do This
              </h3>
              <p className="text-xs text-zinc-300 italic border-l-2 border-red-900/50 pl-3">
                {status.contraindications}
              </p>
           </div>
        </div>
      </div>

      {/* EMS Handover Button */}
      <button 
        onClick={() => setEmsMode(true)}
        className="w-full bg-white hover:bg-zinc-200 text-black font-bold py-3 rounded-xl flex items-center justify-center gap-2 shadow-lg transition-colors"
      >
        <Ambulance className="w-5 h-5" />
        EMS Handover Mode
      </button>
    </div>
  );
};

export default StatusHUD;